---

- name: install packages
  package:
    name: "{{ packages }}"
    state: present
  register: install
  when: (packages | d([]) | length) > 0

- name: stop default service
  service:
    name: "{{ item }}"
    state: stopped
  loop: "{{ disable_services }}"
  when: install|d() and install.changed

- name: disable default service on Linux
  service:
    name: "{{ item }}"
    enabled: no
  loop: "{{ disable_services }}"
  when:
    - ansible_system == 'Linux'
    - install|d() and install.changed

- name: disable default service on FreeBSD
  include_tasks: sysrc.yml
  vars:
    key: "{{ item }}_enable"
    value: "NO"
  loop: "{{ disable_services }}"
  when:
    - ansible_system == 'FreeBSD'
    - install|d() and install.changed
