---

- block:
    - include_tasks: context.yml

    - include_tasks: accounts.yml
      vars:
        accounts_groups: "{{ minecraft_server_groups }}"
        accounts_users: "{{ minecraft_server_users }}"

    - include_tasks: workspace.yml
      vars:
        workspace_fs: "{{ minecraft_server_dir }}"
        workspace_directories: "{{ minecraft_server_directories }}"

    - include_tasks: install_packages.yml
      vars:
        packages: "{{ minecraft_server_packages }}"
        disable_services: []

    - include_tasks: setup_minecraft_server.yml
      when: minecraft_mode in ['simple', 'basic']

    - include_tasks: setup_cross_minecraft_server.yml
      when: minecraft_mode == 'cross'

    - include_tasks: setup_minecraft_service_std.yml

    - include_tasks: setup_minecraft_service_daemontools.yml

  when: want_minecraft_server

- name: "set has_minecraft_server to {{ want_minecraft_server }}"
  set_fact:
    has_minecraft_server: "{{ want_minecraft_server }}"
