---

- name: deploy minecraft server jar
  get_url:
    url: "{{ minecraft_server_jars[minecraft_server_version] }}"
    dest: "{{ minecraft_server_instance_dir }}/minecraft_server.{{ minecraft_server_version }}.jar"
    mode: 0444
    owner: "{{ minecraft_server_user }}"
    group: "{{ minecraft_server_group }}"

- name: deploy eula.txt
  copy:
    src: eula.txt
    dest: "{{ minecraft_server_instance_dir }}/eula.txt"
    owner: "{{ minecraft_server_user }}"
    group: "{{ minecraft_server_group }}"
    mode: 0644

- name: deploy minecraft-server script
  template:
    src: minecraft-server
    dest: "{{ minecraft_server_instance_dir }}/minecraft-server"
    owner: "{{ minecraft_server_user }}"
    group: "{{ minecraft_server_group }}"
    mode: 0755

- name: deploy tmux minecraft-server scripts
  template:
    src: "{{ item }}"
    dest: "{{ minecraft_server_instance_dir }}/{{ item }}"
    owner: "{{ minecraft_server_user }}"
    group: "{{ minecraft_server_group }}"
    mode: 0755
  loop:
    - tmux_minecraft-server_start
    - tmux_minecraft-server_stop
    - tmux_minecraft-server_backup

- name: deploy deamontools service
  block:
    - name: create daemontools base
      file:
        path: "{{ minecraft_server_daemontools_dir }}"
        owner: root
        group: "{{ root_group }}"
        mode: 0755
        state: directory

    - name: create daemontools workspaces
      file:
        path: "{{ minecraft_server_daemontools_dir }}/{{ minecraft_server_instance }}/{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
        state: directory
      loop: "{{ minecraft_server_daemontools_directories_template }}"

    - name: deploy daemontools run scripts
      template:
        src: "svscan/{{ item.path }}"
        dest: "{{ minecraft_server_daemontools_dir }}/{{ minecraft_server_instance }}/{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ minecraft_server_daemontools_scripts_template }}"

    - name: supervise (link) daemontools services
      file:
        src: "{{ minecraft_server_daemontools_dir }}/{{ minecraft_server_instance }}"
        dest: "{{ daemontools_svscan_dir }}/minecraft_server_{{ minecraft_server_instance }}"
        state: link

  when: has_daemontools|d(false)


- name: start standard service
  block:
    - fail:
        msg: "not implemented"

  when: not has_daemontools|d(false)
