---

- name: deploy deamontools service
  block:
    - name: create daemontools base
      file:
        path: "{{ minecraft_server_daemontools_dir }}"
        owner: root
        group: "{{ root_group }}"
        mode: 0755
        state: directory

    - name: create daemontools workspaces
      file:
        path: "{{ minecraft_server_daemontools_dir }}/{{ minecraft_server_instance }}/{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
        state: directory
      loop: "{{ minecraft_server_daemontools_directories_template }}"

    - name: deploy daemontools run scripts
      template:
        src: "svscan/{{ item.path }}"
        dest: "{{ minecraft_server_daemontools_dir }}/{{ minecraft_server_instance }}/{{ item.path }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        mode: "{{ item.mode }}"
      loop: "{{ minecraft_server_daemontools_scripts_template }}"

    - name: supervise (link) daemontools services
      file:
        src: "{{ minecraft_server_daemontools_dir }}/{{ minecraft_server_instance }}"
        dest: "{{ daemontools_svscan_dir }}/minecraft_server_{{ minecraft_server_instance }}"
        state: link

  when: has_daemontools|d(false)


- name: start standard service
  block:
    - fail:
        msg: "not implemented"

  when: not has_daemontools|d(false)
