---

- name: deploy minecraft server jar
  get_url:
    url: "{{ minecraft_server_jars[minecraft_server_version] }}"
    dest: "{{ minecraft_server_instance_dir }}/minecraft_server.{{ minecraft_server_version }}.jar"
    mode: 0444
    owner: "{{ minecraft_server_user }}"
    group: "{{ minecraft_server_group }}"

- name: deploy eula.txt
  copy:
    src: eula.txt
    dest: "{{ minecraft_server_instance_dir }}/eula.txt"
    owner: "{{ minecraft_server_user }}"
    group: "{{ minecraft_server_group }}"
    mode: 0644

- name: deploy minecraft-server script
  template:
    src: minecraft-server
    dest: "{{ minecraft_server_instance_dir }}/minecraft-server"
    owner: "{{ minecraft_server_user }}"
    group: "{{ minecraft_server_group }}"
    mode: 0755

- name: deploy tmux minecraft-server scripts
  template:
    src: "{{ item }}"
    dest: "{{ minecraft_server_instance_dir }}/{{ item }}"
    owner: "{{ minecraft_server_user }}"
    group: "{{ minecraft_server_group }}"
    mode: 0755
  loop:
    - tmux_minecraft-server_start
    - tmux_minecraft-server_stop
    - tmux_minecraft-server_backup
