#!/bin/sh

SCRIPT_NAME="${0##*/}"
SCRIPT_RPATH="${0%$SCRIPT_NAME}"
SCRIPT_PATH=`cd "${SCRIPT_RPATH:-.}" && pwd`


if [ "$(whoami)" != "minecraft" ]; then
    echo "$0 must be run as minecraft" 1>&2
    exit 1
fi

cd "$SCRIPT_PATH" &&
    {{ minecraft_java_dir }}/bin/java -Xmx4G -Xms4G -jar minecraft_server.{{ minecraft_server_version }}.jar nogui
